/****** Object:  Table [dbo].[STK_USER]    Script Date: 5/6/2016 9:29:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STK_USER](
	[EM_ID] [nvarchar](50) NOT NULL,
	[EM_PASS] [nvarchar](50) NULL,
	[EM_PERMISSION] [nchar](10) NULL,
	[EM_FLAG] [nchar](10) NULL,
	[EM_NAME] [nvarchar](50) NULL,
	[EM_SURNAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_STK_USER] PRIMARY KEY CLUSTERED 
(
	[EM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


